package snowflake

import (
	"sync"
	"testing"
	"time"
)

func TestResolveNodeIDPrefersExplicitEnv(t *testing.T) {
	t.Setenv(NodeIDEnvVar, "42")
	t.Setenv(renderServiceIDEnvVar, "srv-production")

	if got := resolveNodeID(); got != 42 {
		t.Fatalf("resolveNodeID() = %d, want 42 (explicit env must win over service hash)", got)
	}
}

func TestResolveNodeIDRejectsOutOfRangeExplicitEnv(t *testing.T) {
	// 越界值不能被截断成一个合法节点号：那会静默落到别的节点空间上。
	// 此处应回退到哈希路径，而非使用 256。
	t.Setenv(NodeIDEnvVar, "256")
	t.Setenv(renderServiceIDEnvVar, "srv-production")

	hashed := resolveNodeID()
	if hashed < 0 || hashed > MaxNodeID {
		t.Fatalf("resolveNodeID() = %d, want a value within [0, %d]", hashed, MaxNodeID)
	}

	t.Setenv(NodeIDEnvVar, "")
	if fallback := resolveNodeID(); fallback != hashed {
		t.Fatalf("out-of-range explicit env should fall back to the hash path: got %d, want %d", hashed, fallback)
	}
}

func TestResolveNodeIDDefaultsToZeroWithoutEnv(t *testing.T) {
	t.Setenv(NodeIDEnvVar, "")
	t.Setenv(renderServiceIDEnvVar, "")

	if got := resolveNodeID(); got != 0 {
		t.Fatalf("resolveNodeID() = %d, want 0 for single-instance deployments", got)
	}
}

func TestResolveNodeIDIsStableForSameServiceID(t *testing.T) {
	t.Setenv(NodeIDEnvVar, "")
	t.Setenv(renderServiceIDEnvVar, "srv-production")

	first := resolveNodeID()
	second := resolveNodeID()
	if first != second {
		t.Fatalf("node ID must be stable across restarts for the same service: got %d then %d", first, second)
	}
	if first < 0 || first > MaxNodeID {
		t.Fatalf("resolveNodeID() = %d, want a value within [0, %d]", first, MaxNodeID)
	}
}

// withNode 在固定节点号下执行 body，并把内部时钟锚定到 startMilli。
// 两个节点必须落在同一毫秒上，否则「ID 不重复」只是因为时间不同，
// 无法证明节点位真的把 ID 空间切开了。
func withNode(t *testing.T, node int64, startMilli int64, body func()) {
	t.Helper()

	previousNode, previousLast, previousSequence := nodeIDValue, sfLastTime, sfSequence
	nodeIDOnce = sync.Once{}
	nodeIDOnce.Do(func() {})
	nodeIDValue = node
	sfLastTime, sfSequence = startMilli, 0
	t.Cleanup(func() {
		nodeIDValue, sfLastTime, sfSequence = previousNode, previousLast, previousSequence
	})

	body()
}

// 节点位的意义就在于此：两个实例共用一个数据库时 ID 空间不得重叠。
// 关键是让两个节点在「同一毫秒、同一序列号区间」上生成，只有节点位不同。
func TestGenerateIDIsolatesNodesSharingOneDatabase(t *testing.T) {
	// 序列位每毫秒只有 maxSequence+1 个槽，取满会触发 waitNextMilli；而下面把
	// 内部时钟锚在未来，等待真实时间追上去会把测试挂死。留足余量即可，
	// 证明节点隔离不需要把序列取满。
	const idsPerNode = 200

	// 锚点必须晚于真实时间，GenerateID 才会走「时钟回拨」分支沿用 sfLastTime，
	// 从而让两个节点稳定落在同一毫秒。用相对偏移而非硬编码常量，避免某天
	// 真实时间越过常量后这个测试静默失去意义。
	sharedTime := time.Now().UnixMilli() + 60_000

	produce := func(node int64) []int64 {
		ids := make([]int64, 0, idsPerNode)
		withNode(t, node, sharedTime, func() {
			for i := 0; i < idsPerNode; i++ {
				ids = append(ids, GenerateID())
			}
		})
		return ids
	}

	firstNodeIDs := produce(1)
	secondNodeIDs := produce(2)

	seen := make(map[int64]struct{}, len(firstNodeIDs)+len(secondNodeIDs))
	for _, id := range firstNodeIDs {
		seen[id] = struct{}{}
	}
	for _, id := range secondNodeIDs {
		if _, collided := seen[id]; collided {
			t.Fatalf("id %d generated by both nodes; shared-database writes would conflict", id)
		}
	}

	// 同时确认两边真的覆盖了同一个毫秒，否则上面的断言是空过的。
	firstTimestamp := firstNodeIDs[0] >> timestampShift
	secondTimestamp := secondNodeIDs[0] >> timestampShift
	if firstTimestamp != secondTimestamp {
		t.Fatalf("nodes generated in different milliseconds (%d vs %d); the isolation assertion proved nothing",
			firstTimestamp, secondTimestamp)
	}
}

func TestGenerateIDIsStrictlyIncreasing(t *testing.T) {
	previous := int64(-1)
	for i := 0; i < 5000; i++ {
		current := GenerateID()
		if current <= previous {
			t.Fatalf("id %d is not greater than previous %d; ORDER BY id pagination would break", current, previous)
		}
		previous = current
	}
}

// 旧 ID 是裸毫秒时间戳。新格式必须整体大于它，否则历史行会排到新行之后。
func TestGenerateIDExceedsLegacyMillisecondIDs(t *testing.T) {
	const legacyID = int64(1_800_000_000_000)

	if got := GenerateID(); got <= legacyID {
		t.Fatalf("GenerateID() = %d, want greater than legacy millisecond id %d", got, legacyID)
	}
}

func TestGenerateIDIsUniqueUnderConcurrency(t *testing.T) {
	const (
		goroutines  = 16
		idsPerRoute = 500
	)

	var waitGroup sync.WaitGroup
	results := make([][]int64, goroutines)
	for routine := 0; routine < goroutines; routine++ {
		waitGroup.Add(1)
		go func(index int) {
			defer waitGroup.Done()
			ids := make([]int64, 0, idsPerRoute)
			for i := 0; i < idsPerRoute; i++ {
				ids = append(ids, GenerateID())
			}
			results[index] = ids
		}(routine)
	}
	waitGroup.Wait()

	seen := make(map[int64]struct{}, goroutines*idsPerRoute)
	for _, ids := range results {
		for _, id := range ids {
			if _, duplicate := seen[id]; duplicate {
				t.Fatalf("duplicate id %d generated under concurrency", id)
			}
			seen[id] = struct{}{}
		}
	}
}

// 序列位耗尽时必须换到下一毫秒，不能溢出进 nodeID 位段冒充别的节点。
func TestGenerateIDDoesNotLeakSequenceIntoNodeBits(t *testing.T) {
	const node = int64(7)

	previousNode, previousLast, previousSequence := nodeIDValue, sfLastTime, sfSequence
	nodeIDOnce = sync.Once{}
	nodeIDOnce.Do(func() {})
	nodeIDValue = node
	sfLastTime, sfSequence = 0, 0
	t.Cleanup(func() {
		nodeIDValue, sfLastTime, sfSequence = previousNode, previousLast, previousSequence
	})

	// 远超单毫秒容量（256），强制触发跨毫秒等待路径。
	for i := 0; i < maxSequence*3; i++ {
		id := GenerateID()
		if encodedNode := (id >> nodeShift) & MaxNodeID; encodedNode != node {
			t.Fatalf("id %d encodes node %d, want %d", id, encodedNode, node)
		}
	}
}
